spring:
  application:
    name: specialroutesservice
  profiles:
    active: default
  cloud:
    config:
      enabled: true
  config:
    # 指定Spring Cloud Config服务器的位置
    import: "optional:configserver:http://configurationservice:8888"
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/